### ISSUE TITLE
POST /v1/ordersのpostal_codeがnumber

### ISSUE THREAD

**Issue by 1amageek** [friday-night/codenberg-api-reference#6]
`POST /v1/orders`の`postal_code`がnumberになっていますが、最上位桁が`0`の場合適切に処理しないと思います。
Stringの方がいいかと思いますがどうでしょう。

**Comment by 104kmr** [comment]
@1amageek ご指摘ありがとうございます。

おっしゃるとおりですね。
内部的にも文字列として扱っていまして、
マニュアル記述ミスでございましたので、
修正いたしました。

**Comment by 104kmr** [comment]
ご指摘の内容に修正しましたので、本件closeします。
